#!/bin/sh

enter_venv() {
    if [ ! -d ${VENV_DIR} ]
    then
        # assuming pyenv is installed
        pyenv install "${PYTHON_VERSION}"
        mkdir -p "${VENV_DIR}"
        cd "${VENV_DIR}"
        pyenv local "${PYTHON_VERSION}"
        ${HOME}/.pyenv/versions/3.12.13/bin/python3.12 -m venv ${VENV_DIR}
        . ${VENV_DIR}/bin/activate
        python3.12 -m pip install open-webui
        exit 0
    else
        . ${VENV_DIR}/bin/activate
    fi
}

closure() {
    #set -x
    local APP_NAME=open-webui
    local PYTHON_VERSION=3.12.13
    local VENV_DIR="${HOME}/.${APP_NAME}-venv"
    enter_venv

    local PORT=11435
    export DATA_DIR="${HOME}/.${APP_NAME}"
    export OPENAI_API_BASE_URL=http://0.0.0.0:11434/v1
    export OPENAI_API_KEY=none

    open-webui serve --port "${PORT}"
}

closure
