FROM centos:7 AS base
ARG DUMMY_USER=dummy
ARG UID_GID=10001
RUN groupadd -g ${UID_GID} ${DUMMY_USER} && useradd -m -u ${UID_GID} -d /${DUMMY_USER}/ -g ${DUMMY_USER} ${DUMMY_USER} && \
yum install -y epel-release && yum update -y && yum clean all
