#!/bin/sh

# ollama list
# ollama ps
# rm -rf ~/.ollama/models/blobs/*partial*
# ollama launch pi
# ollama launch opencode

closure() {
    export OLLAMA_VULKAN=0

    export OLLAMA_CONTEXT_LENGTH=24576
    export OLLAMA_MAX_LOADED_MODELS=1
    export OLLAMA_FLASH_ATTENTION=0
    export OLLAMA_HOST=0.0.0.0:11434
    ollama serve
}

closure
