FROM centos:7 AS dummy
# docker build . --file=images/Dockerfile.centos7 --target=dummy --tag=aashipov/docker:centos7-dummy && docker push aashipov/docker:centos7-dummy
ARG DUMMY_USER=dummy
ARG DUMMY_UID=10001
ARG DUMMY_GID=10001
RUN sed -i -e 's|mirrorlist|#mirrorlist|' \
    -e 's|#baseurl=http://mirror.centos.org/centos/$releasever|baseurl=https://vault.centos.org/7.9.2009|' \
    /etc/yum.repos.d/CentOS-Base.repo && \
    yum -y update && yum -y upgrade && yum -y install file curl wget && yum -y clean all && \
    groupadd -g ${DUMMY_GID} ${DUMMY_USER} && useradd -m -u ${DUMMY_UID} -d /${DUMMY_USER}/ -g ${DUMMY_USER} ${DUMMY_USER}

FROM aashipov/docker:centos7-dummy AS java
# docker build . --file=images/Dockerfile.centos7 --target=java --tag=aashipov/docker:centos7-java && docker push aashipov/docker:centos7-java
ENV JAVA_HOME=/opt/java
ENV PATH=${JAVA_HOME}/bin:${PATH}
RUN mkdir -p ${JAVA_HOME}

FROM aashipov/docker:centos7-java AS jdk25
# docker build . --file=images/Dockerfile.centos7 --target=jdk25 --tag=aashipov/docker:centos7-jdk25 && docker push aashipov/docker:centos7-jdk25
RUN curl -L -o /tmp/java.tar.gz https://github.com/aashipov/openjdk-build/releases/download/1.0.0/jdk25u-linux-x86_64-jdk-25.0.3+9.tar.gz && \
    tar -xzf /tmp/java.tar.gz -C ${JAVA_HOME}/ --strip-components=1 && \
    find "${JAVA_HOME}" -type f -name '*.debuginfo' -exec rm {} \; && \
    find "${JAVA_HOME}" -type f -name '*.diz' -exec rm {} \; && \
    rm -rf ${JAVA_HOME}/demo/ ${JAVA_HOME}/lib/src.zip ${JAVA_HOME}/man/ /tmp/java.tar.gz && \
    java -version && file ${JAVA_HOME}/bin/java
