version: '3.8'

# docker exec aena-postgres psql -U postgres -d postgres -c "select * from destination_data where flight_code ='IBE' and flight_number='5225' and schd_dep_lt::date='2017-01-03'"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

x-volumes:
  &cockroach-volumes
  - ${HOME}/docker-volumes/cockroachdb/cockroach-data/:/cockroach/cockroach-data/:rw
  - ${HOME}/docker-volumes/cockroachdb/certs/:/cockroach/certs/:rw

services:
  cockroach:
    image: ${COCKROACHDB}/${COCKROACH}
    hostname: ${COCKROACH}
    container_name: ${COCKROACHDB}
    restart: unless-stopped
    # If you need a root-less container (as more secure, to directly access database files without repetitive chown, to store database files on a network drive), initialize a root'ed one, stop, chown volume to UID/GID 10001, uncomment line below and restart container
    #user: ${DUMMY_UID}:${DUMMY_UID}
    volumes: *cockroach-volumes
    ports:
      - '5432:26257'
      - '8083:8080'
    healthcheck:
      test: [ 'CMD-SHELL', '${COCKROACH_HEALTHCHECK_CMD}' ]
      interval: 5s
      timeout: 60s
      retries: 100
      start_period: 10s
    env_file:
      - '.env'
    command: start-single-node
